import matter from '../public/matter'
import "./globals.css";

export const metadata = {
  title: "Portfolio App",
  description: "Generated by codewithestella",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
      

    </html>
  );
}
